name: Lint and Test Source Code Before Deploy
on:
  push:
    branches: ["chris/cicd"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: sudo apt update && sudo apt install -y curl

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm

      - name: Install packages with npm
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test Server
        run: |
          npm run preview
          if [ $(curl -o /dev/null -s -w "%{http_code}" http://localhost:4173/ | grep 200) ]
          then
          echo "200 OK"
          else
          exit 1
          fi
          exit 0
