name: Lint and Test Source Code Before Deploy
on:
  push:
    branches: ["chris/cicd"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: sudo apt update && sudo apt install -y curl

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm

      - name: Install packages with npm
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test Server
        run: npm run preview -l "error"
        timeout-minutes: 1
